 // roles -> permissions mapping
export const rolePermissions = {
  guard: [
    "users.read",
    "users.write",
    "visitors.read",
    "visitors.write",
    "sites.read",
    "gates.read",
    "guards.read",
    "assignments.read",
    "assignments.write",
    "logs.read",
  ],
  host: [
    "users.read",
    "users.write",
    "visitors.read",
    "visitors.write",
    "sites.read",
    "gates.read",
    "logs.read",
  ],
  admin: [
    "users.read",
    "users.write",
    "users.update",
    "users.delete",
    "visitors.read",
    "visitors.write",
    "visitors.update",
    "visitors.delete",
    "sites.read",
    "sites.write",
    "sites.update",
    "sites.delete",
    "gates.read",
    "gates.write",
    "gates.update",
    "gates.delete",
    "guards.read",
    "guards.write",
    "guards.update",
    "guards.delete",
    "assignments.read",
    "assignments.write",
    "assignments.update",
    "assignments.delete",
    "logs.read",
    "logs.export",
  ],
  manager: [
    "users.read",
    "users.write",
    "users.update",
    "visitors.read",
    "visitors.write",
    "visitors.update",
    "sites.read",
    "sites.write",
    "sites.update",
    "gates.read",
    "gates.write",
    "gates.update",
    "guards.read",
    "guards.write",
    "guards.update",
    "assignments.read",
    "assignments.write",
    "assignments.update",
    "logs.read",
    "logs.export",
  ],
  visitor: ["visitors.read", "sites.read", "gates.read", "logs.read"],
};
